[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts =
    -v
    --tb=short
    --html=reports/report.html
    --self-contained-html
markers =
    smoke: smoke-тесты доступности
    crud: CRUD-операции
    query: query-параметры
    error: негативные сценарии
    advanced: продвинутые проверки